#pragma once
// Lifted successor generation on the device: the kernels run exactly the matchers the CPU engine runs
// (successor/detail/engine.hpp) over section "plan" of the device task (rl::dev::TaskView).
//
// The pipeline for a chunk of parent states (all launchers are destination-passing: caller-owned buffers, one stream,
// no allocation, no synchronization):
//   1. launch_view        per-state view (fluent and derived unary bitsets, forward/backward row tables) from the set
//                         bits, one warp per state, built in shared memory and stored whole. On
//                         the L4 the views of a chunk should fit in L2 (DeviceBrfs sizes its chunks so): the count and
//                         write kernels then read them from L2, not DRAM;
//   2. launch_count       blocks of 32 states, one lane per state, the block's warps taking the schemas in turn (a
//                         warp shares a schema, mapped schema-major): the matcher's iterative DFS
//                         (fixed order with backward rows, or fail-first forward checking where rl::dev::device_fc
//                         keeps it; witness pruning) counts the bindings into counts[state * S + schema];
//   3. an exclusive scan of the counts (launch_scan) gives every (state, schema) segment its first output row: the
//      rows come in canonical order (parent, schema, binding) whatever the launch configuration or timing;
//   4. launch_write       the same DFS emits the segment's rows: label columns and successor words (delete, then add;
//                         rl::expand's width rules; atoms without a slot under lazy slots are reported in a bitmap over
//                         canonical ids, the host interns them in id order and the chunk is rerun, so slot numbering is
//                         deterministic too). Matchers that do not bind in parameter order have their segment sorted
//                         lexicographically first (packed keys in local memory for short segments, a heapsort of the
//                         rows in global memory otherwise): the CPU sorts the same unique keys, so the orders agree.
// The count and write kernels are templated on the object-bitset width OW (1..k_max_ow words; forward checking
// 1..k_max_fc_ow) and the write kernel on the successor-row width (u64 y[WB] with WB = 2, 4, 16 or k_max_words: rows of
// up to 4 words stay in registers); launch_put writes deferred rows by groups of lanes (no row copy per thread). Schemas with conditional effects are written by launch_write_ce: their
// conditional effects run as sub-plans at the DFS leaf. Before the goal test and the counts, launch_axioms closes the
// parents' derived bitsets under the axiom strata. Matchers deeper than k_max_depth (up to k_deep_depth
// parameters and label columns: organic-synthesis' reactions) run in kernels of their own (SchemaSet::deep), a warp
// per search with one lane per parameter. Schemas the device does not run
// (deeper matchers; forward checking with wide object bitsets; conditional effects beyond k_ce_depth, or with deep
// matchers) are generated by the CPU engine and placed into their segments by launch_place_host.
// The kernels live in lifted.cu, lifted_ce*.cu (per row width), lifted_deep*.cu and axioms.cu (cuda/src; shared device
// code in lifted_device.cuh).
//
// Device-code subset: included by .cu files compiled by nvcc as C++20; POD, raw pointers and cudaStream_t.

#include "mymyr/rl/task_arrays_view.hpp"

#include <cuda_runtime_api.h>

namespace mymyr::cuda::lifted
{
/// Deepest matcher (free parameters) and widest object bitset the device kernels run; others use the CPU fallback.
inline constexpr u32 k_max_depth = rl::dev::k_max_matcher_depth;
inline constexpr u32 k_max_ow = 8;
/// Widest state rows of the successor kernels (words).
inline constexpr u32 k_max_words = 64;
/// Forward checking keeps a domain stack of (depth + 1) x depth x OW words per thread: limited to OW <= 4.
inline constexpr u32 k_max_fc_ow = rl::dev::k_max_fc_ow;
/// Binding columns of the kernels' label rows.
inline constexpr u32 k_max_label = k_max_depth;
/// Deep matchers: the deepest matcher and widest label of the deep kernels (SchemaSet::deep: a warp's lanes, one per
/// parameter) and their widest object bitsets.
inline constexpr u32 k_deep_depth = rl::dev::k_deep_matcher_depth;
inline constexpr u32 k_deep_ow = 4;
/// Conditional effects on the device: condition matchers with fixed order and at most this many free (forall)
/// parameters run as sub-plans at the DFS leaf; schemas with other conditional effects stay on the CPU fallback.
inline constexpr u32 k_ce_depth = 4;
/// Single-instance count and write launches of at most this many rows (their capacity) search each (state, schema)
/// segment by a warp, its lanes splitting the search; larger launches give each state a lane.
inline constexpr u32 k_warp_rows = 1024;

/// Parent states of a chunk on the device (rows of `words` words, `stride` words apart) and their derived bitsets
/// (axioms: launch_axioms, or the CPU evaluator when the axioms are beyond the kernels).
struct Parents
{
    const u64* data = nullptr;
    u64 stride = 0;
    u32 words = 0;
    u32 rows = 0;
    const u64* derived = nullptr;  // [rows, derived_words] or null
    u32 derived_words = 0;
    // The live rows as a device count (null: all `rows`). Rows at or past *rows_dev are absent: no view, goal,
    // count, row or derived atoms; `rows` is then the capacity a launch is sized for (capturable chunks, whose row
    // counts the host does not read)
    const u32* rows_dev = nullptr;
};

/// The per-state views of a chunk: [rows, words] with words = view_rows * OW.
struct Views
{
    u64* data = nullptr;
    u64 words = 0;
};

/// Which schemas a count / write launch runs.
struct SchemaSet
{
    const u32* schemas = nullptr;  // device schema ids of this launch (all fixed-order or all forward checking)
    u32 count = 0;
    u32 num_schemas = 0;  // S: segments per state
    u32 witness = 1;      // 1: the matcher with witness pruning (plan_schema pre0), 0: pre1
    u32 canonical = 1;    // sort the segments of matchers that do not bind in parameter order
    u32 fc = 0;           // the launch's matchers use forward checking
    u32 deep = 0;         // the launch's matchers are deeper than k_max_depth (single-instance count / write only)
    u32* work = nullptr;  // deep: deep_work_words(rows x count) device words, the launch's scratch
    u32 budget = 0;       // deep: the first pass's search nodes per segment (0: the kernels' own, scaled to the launch)
};

/// The deep launches' scratch (SchemaSet::work) for `segments` (state, schema) segments: k_deep_ctl control words
/// (queues and counters; each deep launch zeroes them on its stream), then per segment a place in the list of segments
/// left to the second pass and its three counters. One scratch serves the deep launches of a stream in turn.
inline constexpr u32 k_deep_ctl = 4;
[[nodiscard]] constexpr u64 deep_work_words(u64 segments) noexcept { return k_deep_ctl + 4 * segments; }

/// Label rows of a chunk: binding [capacity, label_width] (u32; 0xFFFFFFFF past the schema's arity), schema and
/// parent (row of the parent in the chunk, plus parent_base) per row; each array may be null (not written). Rows at or
/// past capacity are not written (their widths and missing atoms still count, see SuccessorRows). Segments sorted in
/// global memory use the binding rows, or `scratch`: with scratch_indexed, scratch has scratch_rows rows indexed like
/// the label rows; otherwise it holds scratch_rows rows for the one segment that straddles the capacity. `error` (one
/// u32) gets bit 0 when a segment finds no room to sort. With `live` set, a write whose *live is 0 writes nothing
/// (a chunk the device halted: its rows are redone; no widths or missing atoms either).
struct Labels
{
    u32* binding = nullptr;
    u32* schema = nullptr;
    u32* parent = nullptr;
    u64 capacity = 0;
    u32 label_width = 0;
    u32 parent_base = 0;
    u32* scratch = nullptr;
    u64 scratch_rows = 0;
    u32* error = nullptr;
    u32 scratch_indexed = 0;
    const u32* live = nullptr;
};

/// Successor rows of launch_write.
struct SuccessorRows
{
    u64* words = nullptr;  // [capacity, out_words] (null: widths and missing atoms only)
    u32 out_words = 0;
    u32* words_needed = nullptr;  // atomicMax of the trimmed width of the rows that do not fit out_words (rl::expand)
    u32* missing_flag = nullptr;  // set to 1 when an added atom has no slot (lazy slots)
    u32* missing_bits = nullptr;  // bitmap over canonical ids [(atom_total + 31) / 32]
    /// Nonzero: launch_write (no conditional effects) sets the labels of the rows below the capacity and leaves
    /// their successor words to launch_put (Labels::binding required). A segment's rows are one thread's search, its
    /// successors one thread each: a state with many successors (gripper's pick over 80 balls) no longer bounds a
    /// launch with its one thread's writes.
    u32 deferred = 0;
};

/// Goal test of the parents: out[0] += the goal states among them, out[1] = min(out[1], row of the first one).
cudaError_t launch_goal_count(const rl::dev::TaskView& t, Parents p, u32* out, cudaStream_t s);
/// out[i] = 1 iff row i of `states` (rows of `words` words) is a goal state, for i < min(n, *n_dev) (n_dev may be
/// null). Goals with derived literals need the CPU (their derived bitsets).
cudaError_t launch_goal_rows(const rl::dev::TaskView& t, const u64* states, u32 words, u64 n, const u32* n_dev, u8* out,
                             cudaStream_t s);
/// bad_row = min(bad_row, i) for every row i that sets a bit at or past `limit` (atom slots the task has not assigned).
cudaError_t launch_check_rows(const u64* data, u64 stride, u32 words, u64 rows, u32 limit, u32* bad_row, cudaStream_t s);

/// Views of `p` into v.data (one warp per state). derived bitsets are applied with the derived view ops.
cudaError_t launch_view(const rl::dev::TaskView& t, Parents p, Views v, cudaStream_t s);

/// counts[state * S + schema] = bindings of `set`'s schemas (entries of other schemas are not written).
cudaError_t launch_count(const rl::dev::TaskView& t, Parents p, Views v, SchemaSet set, u32* counts, cudaStream_t s);

/// Writes the rows of every segment at offsets[state * S + schema] (an exclusive scan of the counts): labels and
/// successor rows (see Labels, SuccessorRows); rows past labels.capacity are clipped. The parents and the output rows
/// are at most k_max_words words wide.
cudaError_t launch_write(const rl::dev::TaskView& t, Parents p, Views v, SchemaSet set, const u32* offsets, Labels labels,
                         SuccessorRows out, cudaStream_t s);
/// launch_write for schemas with conditional effects (lifted_ce.cu): at each row every conditional effect's
/// condition matcher (fixed order, at most k_ce_depth free parameters) runs with the schema's binding prebound over the
/// parent's view and derived bitset (p.derived), and each firing binding adds its deletes and adds to the successor.
cudaError_t launch_write_ce(const rl::dev::TaskView& t, Parents p, Views v, SchemaSet set, const u32* offsets, Labels labels,
                            SuccessorRows out, cudaStream_t s);
/// The successors of the rows deferred launch_write calls labeled (SuccessorRows::deferred; `out` as theirs, its
/// `deferred` ignored): every row below min(total, labels.capacity), total = offsets[live rows * num_schemas], by a
/// group of lanes as wide as half the wider of the parent and output rows (the row's words coalesced, no copy of
/// the row per thread), the groups striding over the rows (a grid for about `rows_hint` rows). A row's segment comes
/// from its parent and schema labels (or a search of the offsets), its binding from its label row. Only rows of
/// schemas with deferred[schema] set (deferred [num_schemas], device; null: every schema) are written; nothing when
/// *labels.error is set (a write that left a segment unlabeled: the caller redoes the chunk).
cudaError_t launch_put(const rl::dev::TaskView& t, Parents p, u32 num_schemas, const u8* deferred, const u32* offsets,
                       Labels labels, SuccessorRows out, u64 rows_hint, cudaStream_t s);

// ------------------------------------------------------------------------------------------------ axioms

/// The derived bitsets of a chunk (axioms.cu). Derived atoms have their own slot space (task/atom_index.hpp): row i
/// holds the derived slots true in parent i, `words` words each.
struct Derived
{
    u64* data = nullptr;  // [rows, words]
    u32 words = 0;
    /// Per axiom (in plan_axiom order): {predicates of its stratum that its body reads, as bits of their index in the
    /// stratum's head list; the bit of its head}. Semi-naive at the predicate level: in the rounds of a recursive
    /// stratum an axiom runs again only if a predicate it reads gained atoms. Null: every axiom in every round.
    const u64* reads = nullptr;
    u32* missing_bits = nullptr;  // lazy slots: bitmap over canonical ids of the derived atoms without a slot
    u32* missing_flag = nullptr;
};

/// The strata on the host side, for launch_axioms: per stratum its first axiom and its axiom count (as in section
/// "plan"), and whether it runs flat: no body of it reads a head predicate of it (so it is not recursive either, and
/// the order of its axioms does not matter).
struct Strata
{
    const u32* begin = nullptr;
    const u32* count = nullptr;
    const u8* flat = nullptr;
    u32 n = 0;
};

/// Axiom strata on the device: the derived bitsets
/// of the parents, closed under the axioms stratum by stratum as the CPU's AxiomEvaluator does. A new derived atom goes
/// into the bitset and into the parent's view at once. A flat stratum takes one lane per (parent, axiom), setting the
/// bits atomically; the other strata take one lane per parent through the CPU's rounds: the axioms in order, one round
/// when not recursive, else rounds to the fixpoint (unique: the strata are stratified). Consecutive non-flat strata
/// share a launch. `v` holds the views of the fluent atoms (launch_view without derived bitsets) and gets the derived
/// atoms added. p.derived is ignored. Atoms without a slot (lazy slots) are reported in the missing bitmap and left
/// out: the caller interns them and reruns views and axioms. `fc`: some body runs forward checking on the device
/// (rl::dev::k_mc_device_fc; t.ow <= k_max_fc_ow). Body matchers are at most k_max_depth deep. `strata` must match t's.
cudaError_t launch_axioms(const rl::dev::TaskView& t, Parents p, Views v, Derived d, bool fc, const Strata& strata,
                          cudaStream_t s);

/// launch_goal_rows with the rows' derived bitsets ([n, derived_words], for goals with derived literals).
cudaError_t launch_goal_rows_derived(const rl::dev::TaskView& t, const u64* states, u32 words, u64 n, const u64* derived,
                                     u32 derived_words, u8* out, cudaStream_t s);

/// dst[i] = the row order[i] of src (rows of `words` words, `stride` apart; order may be null: row i), zero where
/// order[i] >= src_rows.
cudaError_t launch_gather_rows(const u64* src, u64 stride, u32 words, u64 src_rows, const u32* order, u64 n, u64* dst,
                               cudaStream_t s);

/// Host-generated rows (CPU fallback schemas): row i goes to offsets[segment[i]] + rank[i] (rows at or past `capacity`
/// are dropped): binding, schema = segment % S, parent = segment / S + parent_base, and its words (out_words wide).
struct HostRows
{
    const u32* segment = nullptr;
    const u32* rank = nullptr;
    const u32* binding = nullptr;  // [n, label_width]
    const u64* words = nullptr;    // [n, out_words] (null: no words)
    u64 n = 0;
};
cudaError_t launch_place_host(HostRows h, const u32* offsets, u32 num_schemas, Labels labels, u64* out_words, u32 out_width,
                              cudaStream_t s);

/// Scatters host counts: counts[segment[i]] = value[i].
cudaError_t launch_scatter_counts(const u32* segment, const u32* value, u64 n, u32* counts, cudaStream_t s);

/// Exclusive prefix sum of n u32 values (CUB): temp_bytes() is the scratch launch_scan needs for n values.
[[nodiscard]] u64 scan_temp_bytes(u64 n);
cudaError_t launch_scan(const u32* in, u32* out, u64 n, void* temp, u64 temp_bytes, cudaStream_t s);

/// rl::expand's CSR offsets from the segment offsets: offsets_out[i] = base + seg_offsets[i * S] for i <= rows (the
/// entry at rows * S is the total), as int32.
cudaError_t launch_state_offsets(const u32* seg_offsets, u32 num_schemas, u64 rows, u64 base, i32* offsets_out,
                                 cudaStream_t s);

/// The padded [rows, K] view of a flat expansion (rl::pad on the device; arrays that are null are not written).
struct Padded
{
    u32 K = 0;
    i32* index = nullptr;
    u8* mask = nullptr;
    i32* count = nullptr;
    u64* succ = nullptr;
    u32 words = 0;
    i32* schema = nullptr;
    i32* binding = nullptr;
    u32 label_width = 0;
    u8* goal = nullptr;
    u32* overflow = nullptr;  // set to 1 when some count > K or a successor is past the flat capacity
};
struct Flat
{
    const i32* offsets = nullptr;
    u64 capacity = 0;
    const u64* succ = nullptr;
    u32 words = 0;
    const i32* schema = nullptr;
    const i32* binding = nullptr;
    u32 label_width = 0;
    const u8* goal = nullptr;
};
cudaError_t launch_pad(Flat flat, u64 rows, Padded out, cudaStream_t s);

// ------------------------------------------------------------------------------------------------ picks

/// The environment's per-parent count cache: the successor counts per schema, plus the segments of the recorded
/// schemas, so that a pick there needs no search (launch_count_keys writes it, launch_pick reads it). Row i (at
/// data + i * stride, u32 words) holds
///   [0, S)                    the bindings per schema (launch_count's counts),
///   S, S + 1                  a fingerprint of the parent row (low, high word; row_fingerprint),
///   S + 2 + 2 seg_cap r ...   region r of the recorded schema with region[schema] = r, seg_cap 64-bit words (low,
///                             high u32 word): for a schema with a rank table (rank[schema] != k_none), the bitmap
///                             of its segment's canonical ranks (its first ceil(size / 64) words) when the segment has
///                             more than seg_cap bindings and at least k_rank_density per bitmap word; for the other
///                             recorded schemas, the segment's packed keys in canonical order when it has at most
///                             seg_cap bindings; else the region is not written and the pick searches.
/// Recorded schemas are those whose segment order is the canonical order and whose picks would search every binding
/// (the sorted segments of launch_write under canonical order, ranks in a region or keys within 64 bits; the caller
/// decides which). A rank table (at rank_table + rank[schema]) holds the size of the schema's canonical rank space (the
/// product of its parameters' static domain sizes, the matcher's dom0: at most 64 min(seg_cap, k_max_rank_words)),
/// then [arity, num_objects] the share of object o at parameter i in a binding's rank: o's rank among the objects of
/// parameter i's domain times the product of the later parameters' domain sizes (parameter 0 the most significant, so
/// the ranks order the bindings canonically), k_rank_outside for an object outside the domain; a binding's rank is the
/// sum of its shares. Without recorded schemas (regions 0) a row holds the counts only. A region is written by the one
/// thread that counts its segment (keys: in the matcher's order, then sorted in registers), so the rows do not depend
/// on the launch configuration.
struct CountCache
{
    u32* data = nullptr;
    u64 stride = 0;              // cache_stride(num_schemas, regions, seg_cap)
    u32 num_schemas = 0;         // S
    u32 regions = 0;             // recorded schemas
    u32 seg_cap = 0;             // 64-bit words per region (at most k_max_seg_cap)
    const u32* region = nullptr;  // [S]: the region of a recorded schema, k_none for the others (null: none)
    u32 region_stride = 0;       // multi-instance launches: region is [I, region_stride], row k per instance
    const u32* rank = nullptr;   // as region: the offset of a recorded schema's rank table, k_none: keys (null: none)
    const u32* rank_table = nullptr;
};
inline constexpr u32 k_max_seg_cap = 16;
/// 64-bit words of a region's rank bitmap: at most this many, and at most seg_cap (the counting thread holds the bitmap
/// in registers).
inline constexpr u32 k_max_rank_words = 8;
/// A rank table's share of an object outside the parameter's domain (any sum with it lies past every rank bitmap).
inline constexpr u32 k_rank_outside = 1u << 24;
/// A rank bitmap is written for segments of more than seg_cap bindings with at least this many bindings per 64-bit
/// word of the bitmap (sparse ones cost more memory traffic than their picks' searches).
inline constexpr u32 k_rank_density = 8;
[[nodiscard]] MYMYR_HD constexpr u64 cache_stride(u32 num_schemas, u32 regions, u32 seg_cap)
{
    return regions ? u64{num_schemas} + 2 + 2 * u64{regions} * seg_cap : u64{num_schemas};
}

/// A 64-bit fingerprint of a parent row of `words` words (the count cache's check that it describes the row).
[[nodiscard]] MYMYR_HD constexpr u64 row_fingerprint(const u64* row, u32 words)
{
    u64 h = 0x243F6A8885A308D3ull ^ words;
    for (u32 i = 0; i < words; ++i)
    {
        h ^= row[i];
        h *= 0x9E3779B97F4A7C15ull;
        h ^= h >> 29;
    }
    h ^= h >> 32;
    h *= 0xD6E8FEB86659FD93ull;
    return h ^ (h >> 32);
}

/// launch_count's counts into the cache rows of `p` (c.num_schemas must equal set.num_schemas), with the regions of
/// the recorded schemas among `set`'s; `first` (the first launch over the chunk's rows) writes the fingerprints.
cudaError_t launch_count_keys(const rl::dev::TaskView& t, Parents p, Views v, SchemaSet set, CountCache c, bool first,
                              cudaStream_t s);

/// One chosen successor per parent, for the environment step of cuda/env.hpp: parent i's successor number rank[i] of
/// its (i, schema[i]) segment, in the order launch_write writes the segment (canonical order when set.canonical).
struct Picks
{
    const u32* schema = nullptr;  // [rows]: the schema of the pick (k_none: parent i does not move)
    const u32* rank = nullptr;    // [rows]: the index within the segment
    const u8* fc_of = nullptr;    // [S]: 1 if the device forward checks the schema; a launch takes set.fc's picks
    u32* error = nullptr;         // bit 1: some rank was not found (the counts did not belong to the state)
    CountCache cache;             // the parents' count cache (no regions: every pick searches)
};

/// Finds every pick of `set`'s kind and writes it as launch_write writes a row, at row i of `labels` (capacity >= rows)
/// and of `out` (the successor rows; out.words may be the parents themselves: a row is written after its pick). A pick
/// in a region of the count cache (a recorded schema's rank bitmap, or its keys of a segment of at most seg_cap
/// bindings) is read from the cache, after the row's fingerprint is checked (error bit 1 if it does not match). Others
/// are found by the segment's matcher: segments that launch_write sorts are selected without sorting, by one search
/// into a bitmap of their canonical ranks (rank spaces up to 1024), else by a window of the 32 smallest remaining
/// packed keys per pass, so a pick of rank r costs r / 32 + 1 searches of the segment; the keys (arity x bits per
/// object) must fit 64 bits (pick_keys_fit), otherwise the pick reports error bit 1.
cudaError_t launch_pick(const rl::dev::TaskView& t, Parents p, Views v, SchemaSet set, Picks picks, Labels labels,
                        SuccessorRows out, cudaStream_t s);

/// Whether launch_pick selects in the sorted order for a schema of `arity` over `num_objects` objects.
[[nodiscard]] MYMYR_HD constexpr bool pick_keys_fit(u32 arity, u32 num_objects)
{
    u32 bits = 1;
    while (bits < 32 && (u64{1} << bits) < num_objects)
        ++bits;
    return static_cast<u64>(arity) * bits <= 64;
}

// ------------------------------------------------------------------------------------------------ several instances
// Batches over a task table (rl/task_table.hpp): the rows of one launch are states of different
// instances of one domain (cuda::DeviceTaskTable holds their device views). A kernel thread resolves its row's instance
// once, `views[inst[row]]`, and runs that instance's matchers unchanged; outputs are addressed by row, so the launch
// order changes no result. The instances' tables are OW-strided (domains, static rows, view rows), so a launch takes
// the rows of one object-bitset width (Multi::ow, the kernels' OW) and skips the others; the successor kernels also
// take one row-width bucket per launch (Multi::words_lo / words_hi: the rows whose instance has state words in
// (lo, hi]; the widest bucket of the OW group takes them all). A warp runs as slowly as its slowest lane, so the caller
// groups the rows by instance: launch position j takes row order[j] (a stable permutation grouped by instance).
// Schemas run on the device for every instance (the multi launches have no CPU fallback), and whether a schema's
// matcher forward checks is per instance (Multi::fc_of): a launch of set.fc runs the (row, schema) pairs of its kind.

/// The instances and the row order of a multi-instance launch.
struct Multi
{
    const rl::dev::TaskView* views = nullptr;  // [I] (device): the instances' views
    const u32* inst = nullptr;                 // [rows]: the instance of each row (a batch's task ids)
    const u32* order = nullptr;                // launch position j -> row order[(first + j) * order_stride] (null: row
                                               // first + j); the launch's p.rows positions start at `first`
    u64 order_stride = 1;
    u64 first = 0;
    const u32* order_bad = nullptr;  // device flag (may be null): nonzero means the order is stale, position j is row
                                     // first + j
    const u8* fc_of = nullptr;       // [I, num_schemas]: the instance's matcher of the schema: 0 fixed order, 1 forward
                                     // checking, 2 never applicable (count 0)
    u32 num_schemas = 0;
    u32 instances = 0;               // I: rows with a task id outside [0, I) are skipped (the caller reports them)
    u32 ow = 0;                      // the launch's object-bitset width (launch_view_multi: 0 for every row)
    u32 words_lo = 0, words_hi = 0xFFFFFFFFu;  // the rows whose instance has state words in (lo, hi]
    // A range launch (launch_view_multi, launch_count_keys_multi and launch_pick_multi; the other multi launches reject
    // it): with an order sorted by key (launch_order) and its key starts (starts[k]: the first position of key k's rows,
    // starts[keys] = the rows), the launch takes the positions first + j in [starts[key_lo], starts[key_hi]) and the
    // others return at once, without reading their rows; a stale order (order_bad) takes every position. The other
    // filters (ow, bucket, task ids) still apply, so a range only drops positions whose rows they skip.
    const u32* starts = nullptr;  // [keys + 1] (device; null: every position)
    u32 key_lo = 0, key_hi = 0;
};

/// launch_view over the rows of every instance, or (m.ow nonzero) of the instances of that object-bitset width (one
/// warp per row; views of instance k fill view_rows * ow words of the row's v.words).
cudaError_t launch_view_multi(const Multi& m, Parents p, Views v, cudaStream_t s);
/// launch_count over the rows of m.ow (set: the schemas; entries of other kinds or rows are not written).
cudaError_t launch_count_multi(const Multi& m, Parents p, Views v, SchemaSet set, u32* counts, cudaStream_t s);
/// launch_write over the rows of m.ow in the row-width bucket (m.words_lo, m.words_hi]: the kernels hold a successor in
/// `wb` words (2, 4, 16 or k_max_words, at least m.words_hi; the parent and output rows may be wider, their words past
/// the instance's are zero). No conditional effects.
cudaError_t launch_write_multi(const Multi& m, Parents p, Views v, SchemaSet set, const u32* offsets, Labels labels,
                               SuccessorRows out, u32 wb, cudaStream_t s);
/// Where launch_put_multi puts its rows besides `out`. Unmapped (rows null): row j at row j of out.words, and its
/// goal flag at goal[j]. Mapped (the labeled rows are a part of a larger batch, in scratch): successor k of the
/// part's state at position q (q = its parent label; k = j - offsets[(q - labels.parent_base) * S]) goes to row
/// r = batch_offsets[rows[q]] + k of the batch's outputs, written below `capacity` (the rows past it still count their
/// widths and missing atoms): its successor words (out.words is the batch's), its labels widened to label_width (-1
/// past labels.label_width), schema, parent rows[q] and goal flag. Null outputs are skipped.
struct PutRows
{
    const u32* rows = nullptr;           // [part positions] the batch row of each (null: unmapped)
    const i32* batch_offsets = nullptr;  // [batch rows + 1] the batch's CSR offsets
    u64 capacity = 0;
    u32* binding = nullptr;
    u32 label_width = 0;
    u32* schema = nullptr;
    u32* parent = nullptr;
    u8* goal = nullptr;  // the goal flag of each written row (goals without derived literals; needs out.words)
};
/// launch_put over the rows of every instance (m.ow and the bucket ignored; rows of task ids outside
/// [0, m.instances) have none), every schema's rows (m.num_schemas segments per state), and the outputs of `to`.
cudaError_t launch_put_multi(const Multi& m, Parents p, const u32* offsets, Labels labels, SuccessorRows out,
                             const PutRows& to, u64 rows_hint, cudaStream_t s);
/// launch_count_keys over the rows of m.ow; c.region is [I, c.region_stride]. `first`: this launch writes the rows'
/// fingerprints.
cudaError_t launch_count_keys_multi(const Multi& m, Parents p, Views v, SchemaSet set, CountCache c, bool first,
                                    cudaStream_t s);
/// launch_pick over the rows of m.ow in the bucket (picks.fc_of is ignored: m.fc_of decides the kind).
cudaError_t launch_pick_multi(const Multi& m, Parents p, Views v, SchemaSet set, Picks picks, Labels labels,
                              SuccessorRows out, u32 wb, cudaStream_t s);
/// launch_goal_rows with row i of instance inst[i] (goals without derived literals; 0 for task ids outside [0, instances)).
cudaError_t launch_goal_rows_multi(const rl::dev::TaskView* views, u32 instances, const u32* inst, const u64* states,
                                   u32 words, u64 n, u8* out, cudaStream_t s);
/// The checks of a batch over a table: bad_id = min(bad_id, i) for every row i whose task id is outside [0, instances),
/// and (data not null) bad_row = min(bad_row, i) for every row i that sets a bit at or past its instance's assigned
/// fluent slots (limits [instances]).
cudaError_t launch_check_multi(const u32* limits, u32 instances, const i32* inst, const u64* data, u64 stride, u32 words,
                               u64 rows, u32* bad_id, u32* bad_row, cudaStream_t s);
/// bad_id = min(bad_id, i) for every row i whose task id is outside [0, instances) (tables whose rows run apart).
cudaError_t launch_check_ids(const i32* inst, u32 instances, u64 rows, u32* bad_id, cudaStream_t s);

/// The per-instance expansion of a batch over a table (cuda::DeviceExpander, PerInstance): each instance's rows are
/// gathered into a part (rows[j]: the batch row at part position j) and expanded apart; these put the parts' results
/// back in batch order. launch_part_counts: counts[rows[j]] = offsets[j + 1] - offsets[j] for the part's n positions.
cudaError_t launch_part_counts(const u32* rows, const i32* offsets, u64 n, u32* counts, cudaStream_t s);
/// One part's successors [0, total) (part-local parents and CSR offsets; rows of `words` words, labels of
/// `label_width` columns) to their batch positions: successor j of part position p = parent[j] goes to row
/// batch_offsets[r] + j - offsets[p] of the outputs, r = rows[p] (with `outer`, r = outer[rows[p]]: the part of a part
/// of the batch, cuda::DeviceExpander's per-instance parts of a suite's domain), widened to out_words (zero words) and
/// out_label_width (-1 entries); not written at or past capacity; null outputs are skipped; its parent label becomes r.
/// A group of lanes per successor (the wider of its output row and labels, a power of two, at most a warp) copies its
/// words and labels coalesced.
struct PartScatter
{
    const u32* rows = nullptr;
    const u32* outer = nullptr;
    const i32* offsets = nullptr;
    const i32* batch_offsets = nullptr;
    u64 total = 0;
    const i32* parent = nullptr;
    const u64* succ = nullptr;
    u32 words = 0, out_words = 0;
    const i32* schema = nullptr;
    const i32* binding = nullptr;
    u32 label_width = 0, out_label_width = 0;
    const u8* goal = nullptr;
    u64 capacity = 0;
    u64* out_succ = nullptr;
    i32* out_schema = nullptr;
    i32* out_binding = nullptr;
    i32* out_parent = nullptr;
    u8* out_goal = nullptr;
};
cudaError_t launch_part_scatter(const PartScatter& p, cudaStream_t s);

/// The launch-order keys of a batch's instances: instance k's key key[k] (device [instances]), in [0, count).
struct OrderKeys
{
    const u32* key = nullptr;
    u32 count = 1;
};
/// The launch order of a multi-instance batch: order[j * stride] = the row at position j, pos[row * stride] = its
/// position, sorted by the key of the row's instance (keys.key[inst[row]]: in a table the rank of the instance's launch
/// group and the instance; in a suite its domain's instances come first), stable by row within a key. Task ids outside
/// [0, instances) take key 0, a key at or past keys.count sorts as keys.count - 1. A counting sort over the keys.count
/// keys when they are at most 1024 (and the batch's (key, tile) counts fit the scratch), else CUB's radix sort over
/// their bits; the same order either way. Scratch: order_temp_bytes(n) bytes.
[[nodiscard]] u64 order_temp_bytes(u64 n);
cudaError_t launch_order(const u32* inst, u32 instances, OrderKeys keys, u64 n, void* temp, u64 temp_bytes, u32* order,
                         u32* pos, u64 stride, cudaStream_t s);
/// Sets *bad when the order is not a permutation of [0, n) (pos[order[j]] != j for some j): a batch rearranged or
/// resized since the order was computed.
cudaError_t launch_check_order(const u32* order, const u32* pos, u64 stride, u64 n, u32* bad, cudaStream_t s);
/// Sets *bad unless order / pos are launch_order's order of the batch: a permutation of [0, n) with its inverse, sorted
/// by key and within a key by row (the debug builds' check of every launch order, cuda/src/table_launch.hpp).
cudaError_t launch_check_order_keys(const u32* inst, u32 instances, OrderKeys keys, u64 n, const u32* order,
                                    const u32* pos, u64 stride, u32* bad, cudaStream_t s);
}  // namespace mymyr::cuda::lifted
