# Merges static archives into one, without debug information. Run at install time (install(CODE)) with
#   MYMYR_BUNDLE_OUT      the archive to extend (read, then overwritten with the merge)
#   MYMYR_BUNDLE_INPUTS   the archives to merge into it
#   MYMYR_BUNDLE_SCRATCH  a scratch directory
#   MYMYR_BUNDLE_AR, MYMYR_BUNDLE_STRIP, MYMYR_BUNDLE_LIBTOOL  the tools (libtool on Apple, ar -M elsewhere)
file(REMOVE_RECURSE "${MYMYR_BUNDLE_SCRATCH}")
file(MAKE_DIRECTORY "${MYMYR_BUNDLE_SCRATCH}")

set(_archives "")
set(_index 0)
foreach(_in IN LISTS MYMYR_BUNDLE_OUT MYMYR_BUNDLE_INPUTS)
    math(EXPR _index "${_index} + 1")
    get_filename_component(_name "${_in}" NAME)
    set(_copy "${MYMYR_BUNDLE_SCRATCH}/${_index}_${_name}")
    file(COPY_FILE "${_in}" "${_copy}")
    list(APPEND _archives "${_copy}")
endforeach()

if(MYMYR_BUNDLE_STRIP)
    if(APPLE)
        set(_strip_flags -S)
    else()
        set(_strip_flags --strip-debug)
    endif()
    foreach(_a IN LISTS _archives)
        execute_process(COMMAND "${MYMYR_BUNDLE_STRIP}" ${_strip_flags} "${_a}" RESULT_VARIABLE _rc ERROR_VARIABLE _err)
        if(NOT _rc EQUAL 0)
            message(FATAL_ERROR "mymyr: stripping ${_a} failed: ${_err}")
        endif()
    endforeach()
endif()

set(_merged "${MYMYR_BUNDLE_SCRATCH}/merged.a")
if(APPLE)
    execute_process(COMMAND "${MYMYR_BUNDLE_LIBTOOL}" -static -o "${_merged}" ${_archives}
        RESULT_VARIABLE _rc ERROR_VARIABLE _err)
else()
    set(_script "CREATE ${_merged}\n")
    foreach(_a IN LISTS _archives)
        string(APPEND _script "ADDLIB ${_a}\n")
    endforeach()
    string(APPEND _script "SAVE\nEND\n")
    file(WRITE "${MYMYR_BUNDLE_SCRATCH}/merge.mri" "${_script}")
    execute_process(COMMAND "${MYMYR_BUNDLE_AR}" -M INPUT_FILE "${MYMYR_BUNDLE_SCRATCH}/merge.mri"
        RESULT_VARIABLE _rc ERROR_VARIABLE _err)
endif()
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "mymyr: merging static archives into ${MYMYR_BUNDLE_OUT} failed: ${_err}")
endif()
file(COPY_FILE "${_merged}" "${MYMYR_BUNDLE_OUT}")
file(REMOVE_RECURSE "${MYMYR_BUNDLE_SCRATCH}")
